# Task-2: Descriptive Analysis

In [3]:
import pandas as pd

# Load the dataset
file_path = r'C:\Users\91702\Dataset .csv'
data = pd.read_csv(file_path)

# Calculate basic statistical measures for numerical columns
numerical_columns = ['Average Cost for two', 'Longitude', 'Latitude', 'Price range', 'Aggregate rating', 'Votes']
statistics = data[numerical_columns].describe().T
statistics['median'] = data[numerical_columns].median()
print("Basic Statistical Measures:")
print(statistics)

# Distribution of Country Code
country_code_distribution = data['Country Code'].value_counts()
print("\nDistribution of Country Code:")
print(country_code_distribution)

# Distribution of City (Top 10)
city_distribution = data['City'].value_counts().head(10)
print("\nDistribution of City (Top 10):")
print(city_distribution)

# Distribution of Cuisines (Top 10)
cuisines_distribution = data['Cuisines'].value_counts().head(10)
print("\nDistribution of Cuisines (Top 10):")
print(cuisines_distribution)

# Identify top cuisines and cities with the highest number of restaurants
top_cuisines = data['Cuisines'].value_counts().head(10)
top_cities = data['City'].value_counts().head(10)
print("\nTop Cuisines:")
print(top_cuisines)
print("\nTop Cities with Highest Number of Restaurants:")
print(top_cities)

Basic Statistical Measures:
                       count         mean           std         min  \
Average Cost for two  9551.0  1199.210763  16121.183073    0.000000
Longitude             9551.0    64.126574     41.467058 -157.948486
Latitude              9551.0    25.854381     11.007935  -41.330428
Price range           9551.0     1.804837      0.905609    1.000000
Aggregate rating      9551.0     2.666370      1.516378    0.000000
Votes                 9551.0   156.909748    430.169145    0.000000

                             25%         50%         75%            max  \
Average Cost for two  250.000000  400.000000  700.000000  800000.000000
Longitude              77.081343   77.191964   77.282006     174.832089
Latitude               28.478713   28.570469   28.642758      55.976980
Price range             1.000000    2.000000    2.000000       4.000000
Aggregate rating        2.500000    3.200000    3.700000       4.900000
Votes                   5.000000   31.000000  131.000000   10934.000000

                          median
Average Cost for two  400.000000
Longitude              77.191964
Latitude               28.570469
Price range             2.000000
Aggregate rating        3.200000
Votes                  31.000000

Distribution of Country Code:
1      8652
216     434
215      80
30       60
214      60
189      60
148      40
208      34
14       24
162      22
94       21
184      20
166      20
191      20
37        4
Name: Country Code, dtype: int64

Distribution of City (Top 10):
New Delhi       5473
Gurgaon         1118
Noida           1080
Faridabad        251
Ghaziabad         25
Bhubaneshwar      21
Amritsar          21
Ahmedabad         21
Lucknow           21
Guwahati          21
Name: City, dtype: int64

Distribution of Cuisines (Top 10):
North Indian                      936
North Indian, Chinese             511
Chinese                           354
Fast Food                         354
North Indian, Mughlai             334
Cafe                              299
Bakery                            218
North Indian, Mughlai, Chinese    197
Bakery, Desserts                  170
Street Food                       149
Name: Cuisines, dtype: int64

Top Cuisines:
North Indian                      936
North Indian, Chinese             511
Chinese                           354
Fast Food                         354
North Indian, Mughlai             334
Cafe                              299
Bakery                            218
North Indian, Mughlai, Chinese    197
Bakery, Desserts                  170
Street Food                       149
Name: Cuisines, dtype: int64

Top Cities with Highest Number of Restaurants:
New Delhi       5473
Gurgaon         1118
Noida           1080
Faridabad        251
Ghaziabad         25
Bhubaneshwar      21
Amritsar          21
Ahmedabad         21
Lucknow           21
Guwahati          21
Name: City, dtype: int64